@startuml

actor User
entity UserService
entity ProjectService
entity FeedbackService
entity ReviewCategoryService

User -> UserService : login()
User -> UserService : logout()
User -> UserService : signIn()
User -> ProjectService : createProject()
User -> ProjectService : addMember(project, member)
User -> ProjectService : viewProject(project)
User -> FeedbackService : addFeedback(feedback)
User -> FeedbackService : viewFeedbacks(user)
User -> FeedbackService : saveFeedback()
User -> FeedbackService : saveDraft()
User -> ReviewCategoryService : createReviewCategory(project, category)
User -> FeedbackService : editFeedback(feedback)
User -> FeedbackService : deleteFeedback(feedback)
User -> FeedbackService : filterFeedbacks(project, condition)
User -> ReviewCategoryService : editReviewCategory(category)
User -> ReviewCategoryService : deleteReviewCategory(category)

@enduml